services:
  stremio:
    image: tsaridas/stremio-docker:latest
    container_name: stremio
    environment:
      - AUTO_SERVER_URL=1
      - NO_CORS=1
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /srv/stremio:/root/.stremio-server
