services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane@sha256:121456f003da38806f4137e0fcbdf8bc6a1c70ada8caf30be3443644a526c1eb
    container_name: arcane
    restart: unless-stopped
    ports:
      - "3552:3552"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /srv:/app/data/projects
    env_file:
      - .env
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
